### ISSUE TITLE
terminology

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#1039]
~~~
<!-- [rfced] Terminology: We had the following questions related to
     terminology throughout the document.

a) The following terms are used inconsistently. Please let us know if
any updates should be made:

   chunked encoding (1 instance) / chunked coding (1 instance) / chunked transfer coding (2 instances) 

   entity tag (4 instances) / entity-tag (63 instances) 

   HTTP date (1 instance) /HTTP-date (31 instances)

   key/value pairs (4 instances) / name/value pairs (1 instance) / name=value pairs (3 instances)

   transfer coding (13 instances) / transfer-coding (6 instances)


b) The following terms were used inconsistently. We have chosen the
latter form. Please let us know if any updates are necessary:

   cache-control / Cache-Control (2 instances, this term is capped in [CACHING])

   cache-directive / cache directive  (1 instance, [CACHING] uses cache directive in text, cache-directive in abnf) 

   Connection option / connection option (1 instance)  

   Etag / ETag  (2 instances) 

   Expert / expert (following the style of RFC 8126) 

   name space / namespace (2 instances)
-->
~~~

**Comment by mnot** [comment]
a)

* I slightly prefer "chunked transfer coding" although can be convinced for the others
* When not in ABNF, it should be "entity tag".
* Should we just change the one instance of "HTTP date' to "HTTP-date"?
* "name/value pairs", I think.
* "transfer-codings" in [extending HTTP](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.16) should be "transfer codings"; the rest are referring to ABNF.

b)

* "see Cache-Control extensions" should be "see extension cache directives" in [16](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.16); otherwise, use of Cache-Control is correct.
* Use of "cache directive" is correct
* Use of "connection option" is correct
* Use of "ETag" is correct
* Fine, whatever
* Fine, whatever

**Comment by reschke** [comment]
FWIW, this needs to be consistent across all specs.

**Comment by reschke** [comment]
> When not in ABNF, it should be "entity tag".

That will be very disruptive.

**Comment by reschke** [comment]
> > When not in ABNF, it should be "entity tag".
> 
> That will be very disruptive.

I believe we'll need to replace almost all uses of "entity-tag" by "entity tag". PR coming.
