### ISSUE TITLE
Should Semantics assume that field values have been coalesced or just unfolded?

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-core#116]
It is hard to talk about header fields without also noting they might appear across multiple lines via repeated names or obs-fold lines.  My goal has been to describe the coalescing of fields in Messaging and only deal with complete values in Semantics.  However, I think only obs-fold is specific to HTTP/1.x.

For now, we have the following text (currently in crefs) in the "Field Values" section of Semantics:

> This document assumes that any such obs-fold has been replaced with one or more SP octets prior to interpreting the field value, as described in (xref target="line.folding").

**Comment by mnot** [comment]
See also #111

**Comment by mnot** [comment]
I agree `obs-fold` is specific to 1.1.

**Comment by MikeBishop** [comment]
IIRC, we encountered a bug during H2 development where folded headers were packaged up in HPACK, CRLF and all.  However, I'm comfortable declaring that construction a bug unless we have evidence that it's in deployed HTTP/2 stacks.

**Comment by MikeBishop** [comment]
Matthew was able to dig up the old e-mail; [this](https://lists.w3.org/Archives/Public/ietf-http-wg/2015JulSep/0254.html) [happened](https://bugzilla.mozilla.org/show_bug.cgi?id=1197847), [but](http://crbug.com/524041) everyone changed their implementations to disallow it, including the one known implementation that emitted it.  I think we're fine to call it 1.1-only.

**Comment by mnot** [comment]
I think the cref'd text is good for inclusion. I'd also remove obs-fold from the ABNF in semantics; i.e., it should be processed in h1 specifically, so that at the semantic "layer", it doesn't appear.

Regarding coalesced values - ISTM that that we can; H1-messaging (and other versions, if they allow such serialisations) can say that you forward header fields without knowing anything about them, but when we deal with them at the semantic level, you only deal with the coalesced value. Doing that would probably also simplify #111.

**Comment by mnot** [comment]
Waiting for #111.

**Comment by mnot** [comment]
#111 is done; unwaiting.

**Comment by mnot** [comment]
#111 took care of distinguishing between a field value and a field line value. As we found, there are still a few places where this distinction need to be made in semantics (e.g., regarding cookies).

Will do a PR to make adjustments to semantics.
