### ISSUE TITLE
Request Cache-Control directives

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#129]
currently fall under the MUST in [7234 5.2](https://httpwg.org/specs/rfc7234.html#cache-request-directive). However, they aren't honoured by most browsers, most CDNs, most reverse proxies, and unevenly honoured by forward proxies.

**Comment by mnot** [comment]
There's also a requirement in [Constructing Responses from Caches](https://httpwg.org/specs/rfc7234.html#constructing.responses.from.caches), although only regarding `no-cache` and `no-store`, not the rest.

There are a few things to unpack here:

* CDNs and reverse proxies don't pay attention to many/any CC request directives, and probably shouldn't.
* [Browser caches](https://wpt.fyi/results/fetch/http-cache/cc-request.html?label=stable&aligned=true are pretty consistent about `CC: no-cache`, less so about `no-store`, and all over the map about `min-fresh`, `max-stale` et al. 
* Last I checked forward proxies were pretty good with everything.

I think we can craft requirements that only apply to forward proxies but not reverse ones. Question is what do browsers want to do here? /cc @annevk

**Comment by annevk** [comment]
What browsers want with `Cache-Control` is probably better answered by @mayhemer @ddragana @MattMenke2 @youennf et al.

**Comment by royfielding** [comment]
I am pretty sure the original intent of these requirements were for caches not controlled by the origin (e.g., CDNs and reverse proxies were not considered caches when those requirements were made). I am sure the intent was to ensure semantic transparency, which is also subject to origin control.

My opinion has always been that they should be an optional preference, not hard requirements, since a single user's desire for semantic transparency does not automatically override a site's need for availability under load.  I was out-hummed on that a long time ago (1996-ish).

Apache httpd implements them as specified. I would prefer it be a config option that might be dynamically adjusted based on whether it is operating as a shared cache, a reverse proxy, or under load.

**Comment by mcmanus** [comment]
in bkk: make this advisory - don't make it universally by default
