### ISSUE TITLE
duplicate pasted text in s-maxage

### ISSUE THREAD

**Issue by royfielding** [httpwg/http-core#264]
The commit d4695a3e422f677d880dc64504c492bf71b6039d for #161 added a paragraph to s-maxage that contains the directive must-revalidate. I think this was supposed to say s-maxage and worded for shared caches?

**Comment by mnot** [comment]
Sorry, been travelling.

This was intentional (although I forgot to update the directive name). `s-maxage` implies `proxy-revalidate`, which implies `must-revalidate`. That seems like a lot of indirection in the definition.

I agree this wasn't a great way to do it, though. I think the options are:

1. Leave it as is (i.e., two levels of indirection).
2. Leave it as is, but use linking more explicitly so that the indirections can be followed more easily (at least in HTML renderings).
3. Inline the appropriate text from `must-revalidate` into both `proxy-revalidate` and `s-maxage`.

I think those are ordered according to my preferences, least to most.

(I strongly suspect many people don't realise `s-maxage` has these semantics, because of it having a name similar to `max-age`. Making them inline rather than referenced might help)

**Comment by royfielding** [comment]
I agree with the conclusion, but am pretty sure that you meant to say s-maxage in that section defining s-maxage. That's all I changed, so it should be fine unless you wanted to add more text to explain why. I don't think it is necessary to explain more because adding s-maxage implies the server wants shared caches to reuse the response.

**Comment by mpdude** [comment]
To me, inlining the consequences was helpful in understanding the consequences. I have a suggestion for a slight rewording in this place in #269.

**Comment by mpdude** [comment]
I agree with @mnot that the additional semantics of `s-maxage` are surprising. In particular due to section 4.2.1, `s-maxage` comes disguised as the "different `maxage` value for shared caches".

So `maxage + public != smaxage`, and the difference is the handling of error cases like with `stale-if-error`?

Could you please try to explain why the additional semantics of `s-maxage` make sense – that is, why did you not just make it the alternative TTL for shred caches?

Thank you!

**Comment by royfielding** [comment]
Ah, okay, so the added paragraph had the right directive before but simply doesn’t make any sense given the context.
