### ISSUE TITLE
CONNECT_UDP and request form

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http-core#436]
The Semantics draft [currently prohibits](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#target.resource) all methods other than CONNECT from using the `host:port` request target form.

> However, there are two special, method-specific forms allowed for the request target in specific circumstances:
>
> - For CONNECT (Section 8.3.6), the request target is the host name and port number of the tunnel destination, separated by a colon.
> - For OPTIONS (Section 8.3.7), the request target can be a single asterisk ("*").
>
> See the respective method definitions for details. These forms MUST NOT be used with other methods.

[draft-schinazi-masque-connect-udp](https://www.ietf.org/id/draft-schinazi-masque-connect-udp-00.html#name-the-connect-udp-method) is currently in Call for Adoption, which defines a new method (CONNECT-UDP) using the same form as CONNECT.  MASQUE and HTTP need to sort out this conflict before either draft is published.

**Comment by royfielding** [comment]
I don’t want to give folks the impression that this is a requirement in httpbis. It has been a requirement of HTTP/1.1 since 1995 and that will not change in this revision.

The short answer is that if a new method is defined, it must use a full URI or its absolute path as the request target. No further exceptions are allowed by HTTP because intermediaries, which may have been deployed years ago, need to process messages even when they don’t know the method definition.

**Comment by mnot** [comment]
I think it's far easier for CONNECT-UDP to change its target form.

**Comment by mnot** [comment]
I think this can be closed with no action -- any issue with that?

**Comment by royfielding** [comment]
> I think this can be closed with no action -- any issue with that?

+1

**Comment by MikeBishop** [comment]
It's being tracked in https://github.com/DavidSchinazi/masque-drafts/issues/29, so this issue can be closed pointing to that one.
