### ISSUE TITLE
5.1. Protocol Version

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#496]
This seems out of place, although I understand that versioning is very message-based.

I'd suggest putting it in 15. Extending HTTP?

**Comment by royfielding** [comment]
It's not about extending HTTP. The version number literally exists as a field of the message, or at least inherited by the context of the connection, and must be retained by recipients because of version-specific requirements. That's why we need to define both cases as part of the message abstraction.

**Comment by mnot** [comment]
Fair enough. Can we open the section with a sentence or two that says that it's a field of the message, to give that context? The current text is pretty abstract.
