### ISSUE TITLE
consistent IANA registration tables

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#506]
In Semantics, we have now moved most registration tables back into the IANA considerations sections.

Should we do the same for everything else, @mnot, @royfielding ?

**Comment by royfielding** [comment]
I don't think so, unless a table serves no other purpose than registration. I left the others in the main spec section because they look to be useful there (as content), but I didn't check carefully.

A good test is to remove the table and read the remaining content to see if it is still sufficient to define the values. If so, then the table can go in the IANA section. If not, then we either need the table inside the section as definition (or we need to replace it with other definitional prose).

**Comment by reschke** [comment]
Candidates:

- https://greenbytes.de/tech/webdav/draft-ietf-httpbis-cache-latest.html#field.cache-control

**Comment by royfielding** [comment]
Yep, all good to move.

**Comment by mnot** [comment]
OK, with me, but note that there are two instances of "directives defined below" in the text preceding the cache table that will need to be adjusted.
