### ISSUE TITLE
Semantics talking about Host header field

### ISSUE THREAD

**Issue by kazuho** [httpwg/http-core#511]
Recently I noticed that the host header field is being discussed in [section 6.2.1 of the semantics draft](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#field.host).

I believe that we should
* move the definition of the host header to the HTTP/1.1 messaging draft, and
* discuss about "authority" as a concept in the semantics draft,

as the "host" header is specific to HTTP/1.1 (except for handling of broken HTTP/2 clients)?

**Comment by mnot** [comment]
Hi Kazuho,

We discussed this on the editors' call. Host's semantics aren't specific to HTTP/1.1, even if its requirements are different in other protocol versions. That's why we moved it to Semantics; it's not version-specific (and really very few headers should be).

Closing; if you feel it needs more discussion please request re-opening and we'll do so.

**Comment by kazuho** [comment]
Thank you for the consideration. While I do understand the argument that the semantics of the header field is not version specific, the use is. I've opened a PR that tries to clarify that.
