### ISSUE TITLE
Target-URI is absolute

### ISSUE THREAD

**Issue by mnot** [httpwg/http-core#636]
Considerations for new method should mention that the target URI has to be absolute.

from https://github.com/ietf-wg-masque/draft-ietf-masque-connect-udp/issues/23

**Comment by DavidSchinazi** [comment]
+1, thanks for filing!

**Comment by reschke** [comment]
We currently say:

> A URI reference is resolved to its absolute form in order to obtain the "target URI". The target URI excludes the reference's fragment component, if any, since fragment identifiers are reserved for client-side processing ([RFC3986], Section 3.5).

Isn't that sufficiently clear?

**Comment by DavidSchinazi** [comment]
It wasn't clear to me because I didn't read the whole doc when I was searching for this information.

**Comment by royfielding** [comment]
It's weird to say this because a URI is always in absolute form (part of what makes it Uniform). Only a reference can be relative, like within the request-target of 1.1 (absolute-path) or anything called a URI-reference.

I think what you want to add is a reminder that new method extensions cannot use the host:port or asterisk forms of request target. Note that this only requires a request target in absolute form if the scheme or host:port are necessary to define the target, which they are for CONNECT-UDP.
