### ISSUE TITLE
Semantics: full-duplex related semantics ...

### ISSUE THREAD

**Issue by wenbozhu** [httpwg/http-core#741]
[7.5](https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-14.html#name-response-correlation) briefly touches this topic.

> Responses (both final and interim) can be sent at any time after a request is received, even if it is not yet complete

More explicit descriptions are helpful, such as:

1. responses can be sent at any time, successful for failed ones
2. responses may be completed before requests are completed. This is described for [100-continue](https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-14.html#name-expect) but should not be limited to 100-continue. 
3. for 2), should a client that sees a failure response continues sending the remaining request content?

**Comment by wenbozhu** [comment]
3) is somewhat addressed in [http/1.1 messaging](https://www.ietf.org/archive/id/draft-ietf-httpbis-messaging-14.html#name-failures-and-timeouts) when the server also closes the connection

**Comment by mnot** [comment]
For (1) and (2), we could adjust to say

> All responses, regardless of status code (including non-final responses), can be sent (and complete) at any time...

(3) is situational. We could say something like 'A client that receives a response to its request while that request is still being sent SHOULD continue sending the request, unless some other signal indicates otherwise.' (with appropriate references, perhaps).
