### ISSUE TITLE
Semantics: 7.8 Upgrade

### ISSUE THREAD

**Issue by wenbozhu** [httpwg/http-core#743]
Clarify if the request needs to be the 1st request after a connection is opened.

**Comment by reschke** [comment]
Is there a reason why you ask? Are there problems when it's not the 1st request?

**Comment by wtarreau** [comment]
I'm not aware of any such problem, and for example in haproxy we do support upgrades anywhere.

**Comment by wenbozhu** [comment]
Just a question I had .. which I feel the spec may want to call it out, either 1st request only or no such restriction.

**Comment by mnot** [comment]
Nothing in HTTP depends on where a request is placed upon a connection, because it's a stateless protocol. see last paragraph [here](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#intermediaries) (this is likely to move to `connections` soon, which is more appropriate.

Should we spell this out more clearly there?

**Comment by wtarreau** [comment]
Probably, it never hurts to remind it.
