### ISSUE TITLE
What is the scheme of OPTIONS * ?

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-core#801]
We're trying to work out what to put in the `:scheme` pseudo-header for `OPTIONS *` in HTTP/2 and I don't know what the answer is.  The `:authority`/`Host` thing is clear enough.  `:scheme` is not.

It's possible that HTTP/2 (and /3) can just choose what the answer is here, but it would be good to know.  I've been thinking that it doesn't matter, except that `http + example.com` and `https + example.com` are two different things that might have two different answers, so maybe the right answer is that we need the scheme (as we need `Host`) to properly identify the thing that is answering the question.

If we didn't have `Host`, then I might be inclined to suggest that the empty string is the right answer, because then the request might target "the server that terminated the connection" rather than any identifiable thing.  Of course, a gateway couldn't route that request, but instead would be forced to answer for itself, which makes little sense.

... so an explicit scheme then. ... ?  Does this need to be written down?

See http2-spec#828 for more discussion.  That was originally about `Host` and `:authority`, but I think we cleared that up (modulo the need for some clarifications).

**Comment by royfielding** [comment]
I fail to see why that is any different from deciding which scheme to use for GET. Both are, in fact, references known to the client that is making the request. That client knows what to put in the scheme. Just tell them to do so.

**Comment by martinthomson** [comment]
So if the client is an intermediary that is translating from HTTP/1.1 and all it has is:

```
OPTIONS *
Host: example.com
```

Or worse:

```
OPTIONS *
```

What then?  Are we relying on configuration?

**Comment by martinthomson** [comment]
Oh, I see this now in [Section 3.3 of messaging](https://httpwg.org/http-core/draft-ietf-httpbis-messaging-latest.html#reconstructing.target.uri):

> If the server's configuration (or outbound gateway) provides a fixed URI scheme, that scheme is used for the target URI. Otherwise, if the request is received over a secured connection, the target URI's scheme is "https"; if not, the scheme is "http".

That says to me that all requests have a scheme, which answers the question (at least for me).  I should learn to RTFS.

**Comment by royfielding** [comment]
> So if the client is an intermediary that is translating from HTTP/1.1 and all it has is:
> 
> ```
> OPTIONS *
> Host: example.com
> ```
> 
> Or worse:
> 
> ```
> OPTIONS *
> ```
> 
> What then? Are we relying on configuration?

You found the right section about schemes (for server interpretation), but it isn't needed in this specific case because OPTIONS * is defined as a first-hop request. In fact, that's why we have the asterisk form. An intermediary isn't allowed to forward it. They are only allowed to forward OPTIONS scheme://full/uri.

A client that creates an OPTIONS * request (whether it be a user agent or intermediary) has some reason for making that request of that next hop, which means that they know what scheme to place in the h2/h3 :scheme pseudo-header for that hop even though we don't send that in h1. It's part of the reference that instructed the client to make that request.
