### ISSUE TITLE
What is the correct behavior if HTTP/2.0 is mentioned over HTTP/1.1 syntax?

### ISSUE THREAD

**Issue by reschke** [httpwg/http-core#845]
see https://stackoverflow.com/questions/67700250/what-is-the-correct-behavior-if-http-2-0-is-mentioned-over-http-1-1-syntax

**Comment by annevk** [comment]
I've had that question for clients and the results are... https://github.com/web-platform-tests/wpt/pull/5102.

**Comment by reschke** [comment]
My 2 cents.

It's not 5xx because it's not the server's fault. In particular, 505 would be misleading if the server indeed supports h2.

So it's a 4xx. I tried two servers (google.com and httpd), and they seem to send 400 ("bad request").

Is it worth documenting/recommending this somewhere?

**Comment by RajeevaLochana** [comment]
5xx would not be accurate at all. Also, this should be the same for HTTP/0.9 request with the protocol name mentioned of HTTP/1.1 syntax. Not sure if there is something about this in the HTTP/1.1 RFC. Should probably be added to the HTTP/1.1 RFC

**Comment by royfielding** [comment]
In general, it is not a lower version protocol error when a higher version of the protocol looks like HTTP/1.1, since there was no way to know if some future version is inherently incompatible with 1.1. However, it would be an error for the higher version protocol when that protocol has requirements that are not met by a 1.1-valid request, as is the case for an "HTTP/2.0" request that does exactly begin with the fixed connection preface of h2.

Hence, when a server implements both h1 and h2 on the same connection surface, what does h2 demand in response to an invalid start?

   https://httpwg.org/specs/rfc7540.html#ConnectionHeader

> Clients and servers MUST treat an invalid connection preface as a connection error (Section 5.4.1) of type PROTOCOL_ERROR. A GOAWAY frame (Section 6.8) MAY be omitted in this case, since an invalid preface indicates that the peer is not using HTTP/2.

Which translates directly into a 400 error if the server chooses to respond as HTTP/1.1, or a RST of the connection to indicate a TCP abort, or something like that for TLS.

If a server only implements HTTP/1.1, then it can choose to ignore the version number and respond as if it were an HTTP/1.1 request (just like an HTTP/0.9 server could theoretically respond to an HTTP/1.0 GET request). It cannot, however, respond with HTTP/2.0 as its response version.

**Comment by kazuho** [comment]
I think there is a related question: what if something other than "HTTP/" is specified. For example, "GET / TEAPOT/1.0" or "GET /my COFFEE".

It is my understanding that these requests are invalid in terms of HTTP/1.1. Also, I do not think we specify how these requests should be handled by the server. Therefore, I believe that servers can send a 400.

While I get @royfielding's argument that HTTP/x.y where x.y>1.1 can be handled gracefully, I'm not sure if we need to have different rules for "TEAPOT/1.0" and "HTTP/2.0."

**Comment by royfielding** [comment]
No additional rules are necessary. HTTP/1 is already defined as preferring robustness over precision. HTTP/2+ is already defined as requiring precision. They both work for this case.

**Comment by royfielding** [comment]
IOW, I don't see an interop problem here that needs to be solved by adding more text. A server can always send 400, even to a perfectly good request.

For HTTP/1.x, good clients will get the response they requested, and bad clients will get whatever the server wants to send them. This should not impact intermediaries or caches, unless an intermediary is responsible for sending the invalid protocol identifier and that intermediary has a cache and we think such an intermediary would respect some other requirement we might add in spite of their other shortcomings. This is way outside our domain of control.

We might reasonably talk about "what is the cache key for the request?" if a server foolishly sends a 200 response to a nonsensical request, but I think the spec is long enough already. We need to specify the valid protocol, not all potentially invalid protocols.

**Comment by reschke** [comment]
Based on the discussion I think we can close this.
